### ISSUE TITLE
ipv6calc-db-update.sh won't download files

### ISSUE THREAD

**Issue by lonwillett** [pbiering/ipv6calc#25]
In ipv6calc-db-update.sh, the "skip_download" variable is always set to "true", so it won't download any files. The variable should be set to "false" by default, and only assigned "true" when the "-s" switch is provided.

**Comment by pbiering** [comment]
Thank you for reporting
- introduced with https://github.com/pbiering/ipv6calc/pull/20
- fixed with https://github.com/pbiering/ipv6calc/commit/6d4cd3570aae3a2b2641cf0c067426d9612ec7a3
