### ISSUE TITLE
Build problem on macOS

### ISSUE THREAD

**Issue by nijikon** [pbiering/ipv6calc#3]
I wanted to upgrade Homebrew formula to 0.99.2 but I'm unable to build.

https://gist.github.com/8ecd657bb5d62ea4d605b07acf1cb4de

**Comment by pbiering** [comment]
Not seen on Linux using "clang", can one investigate the root cause for:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

meanwhile I will check why the shared library is built even if "--enable-shared" is not selected

**Comment by pbiering** [comment]
try build applying following patch on top: https://github.com/pbiering/ipv6calc/commit/128cb3b178dde1b9bcadc1b7a334c5eebcc529be
(this would at least skip unnecessary build of the shared library)

**Comment by nijikon** [comment]
@pbiering Nice! It built on all our VMs. Would it be possible to release new version?

**Comment by pbiering** [comment]
Currently, I want to avoid creating a new version. Would it be possible for you to create packages including the small patch until next release is published (like e.g. possible in RPM builds)?

**Comment by nijikon** [comment]
That works on our end, thanks!
