### ISSUE TITLE
"make install" installs source-level tools to the system

### ISSUE THREAD

**Issue by paravoid** [pbiering/ipv6calc#38]
"make install" seems to be installing all of the files under "tools" to (e.g.) /usr/share/ipv6calc/tools.

However, most of these seem to be internal, source-level tools, e.g. regenerating header files out of IEEE databases and such, and are not really useful in the "destionation" system or in /usr.

A real-world problem that arises with this is when building ipv6calc for a distribution, such as Debian.

**Comment by pbiering** [comment]
> Did I get this right?

Yes, some internal databases can be superseeded by local "external" databases.
