### ISSUE TITLE
Please mark 1.0.0 as latest release on GitHub

### ISSUE THREAD

**Issue by ilovezfs** [pbiering/ipv6calc#6]
http://www.deepspace6.net/ says "ipv6calc 1.0.0 was released" but on GitHub the latest release (https://github.com/pbiering/ipv6calc/releases/latest) shows as 0.99.2 (https://github.com/pbiering/ipv6calc/releases), which confuses the Homebrew livecheck system.

Thanks!

**Comment by pbiering** [comment]
Done, sorry, forgotten...
